apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  ports:
  - name: prom-ui
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: server
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: grafana
  name: grafana
spec:
  ports:
  - name: grafana-ui
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    component: grafana
  type: LoadBalancer